### ISSUE TITLE
gradle groovy Error: Could not find or load main class

### ISSUE THREAD

**Issue by TheNotary** [bond-/gradle-groovy-jar-example#5]
I was getting the below error using gradle 4.x and was stuck for almost and hour:

>  java -jar build/libs/*.jar

It turns out @ciis0 is a boss and fixes this in PR #3 by updating the build.gradle to use Gradle 4.0 syntax `sourceSets.main.java.outputDir, sourceSets.main.groovy.outputDir`

**Comment by bond-** [comment]
Sorry @ciis0 This notification somehow fell off my radar. Merged the PR.
